# Generated by Django 4.2 on 2024-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='teck_stocks',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
