# Generated by Django 4.2 on 2024-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0002_riskassessment_teck_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='alternative',
            field=models.CharField(default='0%', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='t_bills',
            field=models.CharField(default='0%', max_length=50),
        ),
    ]
